version: "3.3"

services:
  elastic:
    image: ozlevka/elastic:5.6.3
    environment:
      - "ELASTIC_CMD_OPTIONS=--E network.host=0"
    networks:
      - default
    ports:
      - 9200:9200

  kibana:
    image: ozlevka/kibana:5.6.3
    environment:
       - "KIBANA_CMD=-e http://elastic:9200"
    networks:
      - default
    links:
      - elastic
    depends_on:
      - elastic
    ports:
      - 5601:5601

networks: 
  default:
